### ISSUE TITLE
issue: Island 1 Forest_Puzzle (P3)

### ISSUE THREAD

**Issue by kricha7ds** [hedgestudios/SearchForOmen#162]
**Description:**
During puzzle 3 on Island 1, when Sebastian is stretched from the south eastern pad towards the pad directly above it (north), if action button is used on the boulder, Sebastian incorrectly states that there is a boulder on his back, preventing him from retracting.

**Environment:**
macOS, HEAD at commit #161.
Map: Forest_Puzzle_(P3)

**Steps to reproduce:**
Go to the south eastern pad on the map and have Sebastian stretch to the pad directly north. Next, approach the boulder found on the south eastern pad and press the action button. 

**Expected vs Actual:**
Expected: nothing? Perhaps different dialogue?
Actual: initializes dialogue from Sebastian about a boulder being on this back.

<img width="810" alt="Screen Shot 2019-03-14 at 10 02 38 PM" src="https://user-images.githubusercontent.com/37306581/54407913-6801b000-46a5-11e9-8741-e4610c8d0e09.png">

**Comment by jbrons17** [comment]
Fixed boulder mechanism which tests whether it is on stretch-hog or not
