### ISSUE TITLE
issue: Forest_Puzzle_(P3)

### ISSUE THREAD

**Issue by kricha7ds** [hedgestudios/SearchForOmen#163]
**Description:**
in south eastern pad on puzzle 3, boulder will move across water on tile that Sebastian is not stretched on.

**Environment:**
macOS, HEAD at version #161 

**Steps to reproduce:**
Go to southeastern pad on island 1 puzzle 3, stretch Sebastian across a tile leading back to the central pad and then attempt to move the boulder across to the central pad. 

**Expected vs Actual:**
Expected: boulder should not move across water
Actual: boulder moves across water
<img width="630" alt="Screen Shot 2019-03-14 at 10 18 29 PM" src="https://user-images.githubusercontent.com/37306581/54408461-b2842c00-46a7-11e9-86ef-bee1350134f6.png">

**Comment by jbrons17** [comment]
Fixed boulder system so it won't get stuck on water.
