### ISSUE TITLE
issue: Forest_Puzzle_(P3)

### ISSUE THREAD

**Issue by kricha7ds** [hedgestudios/SearchForOmen#190]
**Description:**
After placing a boulder on the pressure plate located in the eastern section of the map, the second boulder (located south-eastern corner) teleports to the south west pressure plate? In addition, unable to transfer to next map after roadblock has been cleared. 

**Environment:**
macOS, HEAD at version #188 

**Steps to reproduce:**
Go to Puzzle 3 on Island 1 and place the first boulder on the eastern pressure plate. 

**Expected vs Actual:**
Expected: If south west pressure plate is already pressed, then expect the road block to be cleared. If south west pressure plate is not already pressed, then expect nothing to occur (player must take care of placing the second boulder on the south west pressure plate).
Actual: second boulder teleports to south west pressure plate

<img width="815" alt="Screen Shot 2019-03-19 at 8 38 37 PM copy" src="https://user-images.githubusercontent.com/37306581/54655858-07012000-4a89-11e9-87c8-70954bff8bee.png">

**Comment by jbrons17** [comment]
Fixed issue with boulder position tracking
