### ISSUE TITLE
Lava making lag in volcano maps

### ISSUE THREAD

**Issue by jbrons17** [hedgestudios/SearchForOmen#218]
In Maps
24.Final Puzzle1
25.FinalPuzzle2

Maps are lagging very badly since the implementation of lava glow.
Pull request #217 
Expected:Move smoothly, stretch_hog glides.
Actual: lag caused when player moves or stretch_hog stretches.

**Comment by IanSeng** [comment]
Fog effect in map 24 has been removed.

**Comment by IanSeng** [comment]
It works perfectly on my computer.

**Comment by IanSeng** [comment]
issue solved
