### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by jtfwong** [hedgestudios/SearchForOmen#256]
Recommend reading through every dialogue carefully to catch more typos.

<img width="801" alt="Screen Shot 2019-03-22 at 12 46 38 PM" src="https://user-images.githubusercontent.com/43226692/54847125-25426800-4ca3-11e9-8db5-d6ebf65e4f09.png">
<img width="795" alt="Screen Shot 2019-03-22 at 12 47 04 PM" src="https://user-images.githubusercontent.com/43226692/54847129-28d5ef00-4ca3-11e9-95ba-41c79a9eaff2.png">

**Comment by jbrons17** [comment]
Fixed these typos
