### ISSUE TITLE
Textbox hides characters

### ISSUE THREAD

**Issue by jtfwong** [hedgestudios/SearchForOmen#257]
Not a major issue, but would be better if the sprites were not hidden behind the text box. Possible fix is to move the sprites up, or change the camera location
<img width="797" alt="Screen Shot 2019-03-22 at 12 52 06 PM" src="https://user-images.githubusercontent.com/43226692/54847176-5327ac80-4ca3-11e9-8f59-9e734f8e1d2b.png">

**Comment by jbrons17** [comment]
Extended the height of the map
