### ISSUE TITLE
There is no instruction of how to use stretch hog (map: Path_to_Forest)

### ISSUE THREAD

**Issue by IanSeng** [hedgestudios/SearchForOmen#97]
**Description:**
There is no instruction of how to use stretch hog. 

**Environment:**
macOS, version #93Jack

**Expected vs Actual:**
Expected: NPC to provide the information of key to use. 
Actual: No instruction provided

**Comment by jbrons17** [comment]
Now tells the player the controls to use stretch-hog when the player retrieves sebastian
