### ISSUE TITLE
Unexpected system stop/delay after stepping on a tile (Map: Volcano_Peak)

### ISSUE THREAD

**Issue by IanSeng** [hedgestudios/SearchForOmen#98]
**Description:**
Unexpected system stop/delay after steeping on a tile. Screenshot is provided below. 

**Environment:**
macOS, version #93Jack

**Expected vs Actual:**
Expected: -
Actual: System stop/delay 

<img width="518" alt="screen shot 2019-03-05 at 4 17 54 pm" src="https://user-images.githubusercontent.com/35438972/53844231-4d6f5e80-3f62-11e9-8da0-2b7c49422e6d.png">

**Comment by jbrons17** [comment]
This is for the cutscene which will be made soon. Not a glitch just an unfinished part.

**Comment by IanSeng** [comment]
noted! I will close this issue after the cutscene is done.
